server:
  port: 8081
  servlet:
    context-path: /on-boarding

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss,SSS} | %tid | %p | %logger{36} | %msg%n"

spring:
  jpa:
    properties:
      hibernate:
        connection:
          CharSet: utf8mb4
          characterEncoding: utf8
          useUnicode: true

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true